
files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 1
  border-zero:
    - 0
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format: 0
  clean-import-paths: 0
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 0
  function-name-format: 0
  hex-length: 0
  hex-notation:
    - 1
    - style: lowercase
  id-name-format: 0
  indentation:
    - 1
    - size: tab
  leading-zero: 0
  mixin-name-format: 0
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-literals:
    - 1
    - allow-rgba: true
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements: 0
  no-trailing-zero: 0
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  placeholder-in-extend: 1
  placeholder-name-format: 0
  property-sort-order:
    - 1
    - ignore-custom-properties: false
  property-units: 0
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 0
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 0
  variable-for-property:
    - 0
    - properties: []
  variable-name-format: 0
  zero-unit: 0
